### PR TITLE
Fixed typo preventing img from appearing

### PR DESCRIPTION
**Pull request by aayusht**
i have no idea what i'm doing

### CODE REVIEW

**Comment by shiftkey** [comment]
@aayusht I'm not sure what this is supposed to address - could you tell me a bit about the scenario you're seeing and why this isn't rendering?

**Comment by aayusht** [comment]
Just removed the / in the directory name so the gif would show up. I'm new to github (and programming in general,) so sorry if I wasn't descriptive.

**Comment by shiftkey** [comment]
Is this when you're testing locally? I'm curious how you're testing the site, as [the main site](http://carnackeys.com/) seems to be fine...

**Comment by aayusht** [comment]
Oh yeah it was locally. I couldn't access the site earlier but I think I was going to an io site instead or something. Whoops. At least now I know how fork works.

**Comment by shiftkey** [comment]
Yeah, the `.io` URL doesn't work - I don't think I ever bothered to test it, and we have an [CNAME alias configured](https://github.com/Code52/carnackeys.github.io/blob/gh-pages/CNAME) which seems to be working fine.

I'd recommend having a look at [setting up Jekyll locally](https://help.github.com/articles/setting-up-your-github-pages-site-locally-with-jekyll/) if you're interested in making changes to the site and testing them before submitting a PR.

**Pull request closed without merging**
